accounts/urls.py
from django.urls import path
from .views import *
from .import views
#from loginApp import views


app_name = 'accounts'
urlpatterns = [
    path('registration', views.signUp, name='registration'),
    path('login', views.loginView, name='login'),

    path('logout', views.logoutPage, name='logout'),
  
 
]

ecommerce/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('accounts.urls')),
    path('' ,include('products.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
from .import views
#from loginApp import views


app_name = 'products'
urlpatterns = [
    path('', views.indexPage, name='home'),
     path('collection', views.category, name='collection'),
    path('categoryitems/<str:slug>', views.categoryProducts, name='categoryitems'),
    path('categoryitems/<str:cate_slug>/<str:product_slug>/', views.productDetail, name='product_detail'),

    path('add_to_cart',views.addToCart , name='add_to_cart'),
    path('delete_cart_item',views.removeCartItem , name='delete_cart_item'),
    path('cart',views.cartItem , name='cart'),
     path('update_cart',views.updateCartItem , name='update_cart'),
     path('wishes',views.wishList , name='wishes'),
    path('addTowishList',views.WishItems, name='addTowishList'), 
    path('delete_wishlist_item',views.deleteWishListItem, name='delete_wishlist_item'), 

    path('checkout',views.checkoutItems , name='checkout'),
    path('place_order', views.placeOrder, name='place_order'),
    
    path('payment_confirmed/', views.payment_confirmation, name='payment_confirmed'),
   path('my_orders/', views.myOrders, name='my_orders'),
   
    path('view_orders/<str:tk_no>/', views.myOrdersList, name='view_orders'),

    path('proceed-to-pay/', views.razorpaycheckout, name='proceed-to-pay'),


    path('newL/', views.newLink, name='newL'),
     path('itmD/<int:pk>/', views.itmDetails, name='itmD'),
     path('prod-request/',views.productReq, name="prod-request"),
     path('peoduct_list/', views.productListAjax,name='peoduct_list'),

    path('search-product/', views.productSearch,name='search-product'), 
    
]

templates/includes/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
    
</head>

<style>
  .whatsapp-chat{
    border-radius: 50%;
    position: fixed;
    bottom: 10%;
    left: 3%;
  }
</style>
<body>
    <a href="https://wa.me/+2348079385255?text=I'm%20inquiring%20about%20the%20ecommerce%20app`">
      <img src="{% static 'img/whatsapp2.png' %}" width="70px" class="whatsapp-chat" alt="">
    </a>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'products:home' %}active{% endif %}"  aria-current="page" href="{% url 'products:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'products:collection' %}active{% endif %}" href="{% url 'products:collection' %}">Category</a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'products:cart' %}active{% endif %}" href="{% url 'products:cart' %}" >cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'products:wishes' %}active{% endif %}" href="{% url 'products:wishes' %}">Wishlist</a>
              </li>

             
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'products:contact' %}active{% endif %}" href="">contact</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Sign Up
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                
                  {% if not user.is_authenticated %}
                  <li><a class="dropdown-item {% if request.resolver_match.url_name == 'products:registration' %}active{% endif %}" href="{% url 'accounts:registration' %}" style="color: red;">Registration</a></li>
                  <li><a class="dropdown-item {% if request.resolver_match.url_name == 'products:login' %}active{% endif %}" href="{% url 'accounts:login' %}" style="color: red;">login</a></li>
                  <!--<li><hr class="dropdown-divider"></li>-->
                 {% else %}

                 <li><a class="dropdown-item" href="{% url 'accounts:logout' %}" style="color: red;">logout</a></li>
                  {% endif %}
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'products:cart' %}active{% endif %}" href="{% url 'products:newL' %}" >new link</a>
              </li>
            </ul>
            <form class="d-flex" action="{% url 'products:search-product' %}" method="POST">
              {% csrf_token %}
              <input class="form-control me-2" required id="search_item" name="search-items" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% if user.is_authenticated %}
      <h5>Welcome,{{user.first_name}}</h5>
      {% endif %}
    
      
      {% for mess in messages %}
      <h4>{{ mess }}</h4>
      {% endfor %}
<style>
  h5{
   
    color: #0d6efd;
    font-size: 20px;
    text-align: center;
    text-transform: capitalize;
  }
  h4{
    color: #000;
    font-size: 22px;

  }
  .active{
    font-weight: 800;
    color: blue;
   } 
</style>
    


</body>
</html>

templates/includes/slider.html
{% load static %}
<style>
    .carousel-item{
        height: 350px;
        object-fit: cover;
    }
</style>
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/review-1.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/slider-2.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/product-8.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>