accounts/urls.py
from django.urls import path
from .views import *
from .import views
#from loginApp import views


app_name = 'accounts'
urlpatterns = [
    path('registration', views.signUp, name='registration'),
    path('login', views.loginView, name='login'),

    path('logout', views.logoutPage, name='logout'),
  
 
]

ecommerce/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('accounts.urls')),
    path('' ,include('products.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *
from .import views
#from loginApp import views


app_name = 'products'
urlpatterns = [
    path('', views.indexPage, name='home'),
     path('collection', views.category, name='collection'),
    path('categoryitems/<str:slug>', views.categoryProducts, name='categoryitems'),
    path('categoryitems/<str:cate_slug>/<str:product_slug>/', views.productDetail, name='product_detail'),

    path('add_to_cart',views.addToCart , name='add_to_cart'),
    path('delete_cart_item',views.removeCartItem , name='delete_cart_item'),
    path('cart',views.cartItem , name='cart'),
     path('update_cart',views.updateCartItem , name='update_cart'),
     path('wishes',views.wishList , name='wishes'),
    path('addTowishList',views.WishItems, name='addTowishList'), 
    path('delete_wishlist_item',views.deleteWishListItem, name='delete_wishlist_item'), 

    path('checkout',views.checkoutItems , name='checkout'),
    path('place_order', views.placeOrder, name='place_order'),
    
    path('payment_confirmed/', views.payment_confirmation, name='payment_confirmed'),
   path('my_orders/', views.myOrders, name='my_orders'),
   
    path('view_orders/<str:tk_no>/', views.myOrdersList, name='view_orders'),

    path('proceed-to-pay/', views.razorpaycheckout, name='proceed-to-pay'),


    path('newL/', views.newLink, name='newL'),
     path('itmD/<int:pk>/', views.itmDetails, name='itmD'),
     path('prod-request/',views.productReq, name="prod-request"),
     path('peoduct_list/', views.productListAjax,name='peoduct_list'),

    path('search-product/', views.productSearch,name='search-product'), 
    
]

products/forms.py
from datetime import date
from django import forms
from django.contrib.auth.models import User
from django.forms import widgets
from django.forms.widgets import DateInput


from .models import *





class OrderForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField()
    email = forms.CharField()
    phone = forms.CharField()
    address = forms.Textarea()
    city = forms.CharField()
    state = forms.CharField()
    pin_code = forms.CharField()
    country = forms.CharField()
    total_price = forms.FloatField()
    payment_mode = forms.CharField()
  
    

    class Meta:
        model = Order
        fields =('first_name','last_name','email','phone','address', 'city','state','pin_code','country',
                 'total_price','payment_mode') 

        Widget ={
          
            'first_name':forms.TextInput( attrs={'class':'form-control','placeholder':'First Name'}),
            
            'last_name':forms.TextInput( attrs={'class':'form-control'}),
            'email':   forms.TextInput( attrs={'class':'form-control'}),
        
            'phone':forms.TextInput(attrs={'class':'form-control'}),
            'address':   forms.TextInput( attrs={'class':'form-control'}),
            'city':   forms.TextInput( attrs={'class':'form-control'}),
            'state':forms.TextInput( attrs={'class':'form-control'}),
            'pin_code':   forms.TextInput( attrs={'class':'form-control'}),
            'country':   forms.TextInput( attrs={'class':'form-control'}),
            'total_price':   forms.TextInput( attrs={'class':'form-control'}),
            'payment_mode':   forms.TextInput( attrs={'class':'form-control'}),
           
            }
            

products/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import *
from django.http.response import JsonResponse
from accounts .models import *
from django.contrib import  messages
from django.contrib.auth.decorators import login_required
import random
from .forms import *


def indexPage(request):
    trending =Product.objects.filter(trending=1)
   # trending =Product.objects.filter(trending=0)
    context={'trending':trending}
    return render (request, 'shop/index.html',context)



def category(request):
    cate = Category.objects.filter(status=0)
    context ={'category':cate}
    return render (request, 'shop/category.html',context)



def categoryProducts(request,slug):
    if Category.objects.filter(slug = slug).exists():
        products = Product.objects.filter(category__slug =slug) #accessing category slugs
        category_name =Category.objects.filter(slug=slug).first()
        context ={'products':products,'category_name':category_name}

        return render(request,'shop/products.html',context)
    
    else:
        messages.warning(request, 'No category of such found')
        return redirect('products:collection')






def productDetail(request, cate_slug, product_slug):
    if Category.objects.filter(slug=cate_slug, status=0):
        if Product.objects.filter(slug=product_slug,status=0):
            item = Product.objects.filter(slug=product_slug, status=0).first()
            context={'product':item}
            
        else:
           messages.warning(request,"no such item found")  
           return redirect('products:collection')   
    
    else:
        messages.warning(request,"no such item found")
        return redirect('products:home')

    return render(request,'shop/productDetail.html',context)    




def addToCart(request):
    if request.method =="POST":
        if request.user.is_authenticated:
            prod_id =int(request.POST.get('product_id'))
            productCheck = Product.objects.get(id=prod_id)
            print('productCheck:',productCheck)
            if productCheck:
                if Cart.objects.filter(user =request.user.id, product_id =prod_id):
                    return JsonResponse({'status':'Product already exists'})

                else:
                    prod_qty =int(request.POST.get('product_qty'))
                    print('no,it doest exist there')

                    if productCheck.quantity >= prod_qty:
                        Cart.objects.create(user=request.user,product_id =prod_id, product_qty=prod_qty)
                        return JsonResponse({'status':'successfully added'}) 

                    else:
                        return JsonResponse({'status': "Only" +str(productCheck.quantity) + 'quantity available'}) 

            else:
                return JsonResponse({'status':'No such product available'}) 

        else:
            return JsonResponse({'status':'Login to continue'}) 

    else:
        return redirect('/')                 


                                       
@login_required(login_url='accounts/login')
def cartItem(request):
    if request.user:
        cart = Cart.objects.filter(user=request.user)
        count = len(cart)
    else:
        pass 
    context={'cart':cart,'count':count}
    return render(request, 'shop/cart.html',context)



@login_required(login_url='accounts/login')
def updateCartItem(request):
    if request.method =="POST":
        prod_id =int(request.POST.get('product_id'))
        if Cart.objects.filter(user=request.user,product_id =prod_id):
            prod_qty =int(request.POST.get('product_qty'))
            cart = Cart.objects.get(product_id =prod_id, user=request.user)
            cart.product_qty = prod_qty
            cart.save()

            messages.warning(request,"successfully updated")
            return JsonResponse({'status':'Successful'}) 
     
    
    return redirect('/')



@login_required(login_url='accounts/login')
def removeCartItem(request):
    if request.method =="POST":
        prod_id =int(request.POST.get('product_id'))
        if Cart.objects.filter(user=request.user,product_id =prod_id):
            cartitem = Cart.objects.get(user=request.user,product_id =prod_id)
            cartitem.delete()
            return JsonResponse({'status':'Item Successful deleted'}) 
    return redirect('/')    


@login_required(login_url='accounts/login')
def wishList(request):
    wish = WishList.objects.filter(user =request.user)
    context={"wish":wish}
    return render(request,"shop/wishlist.html",context) 



@login_required(login_url='accounts/login')
def WishItems(request):
    if request.method =="POST":
        if request.user.is_authenticated:
            prod_id =int(request.POST.get('product_id'))
            productCheck = Product.objects.get(id=prod_id)
            if productCheck:
                if WishList.objects.filter(user =request.user, product_id =prod_id):
                    return JsonResponse({'status':'Product already in wishlist'}) 

                else:
                    WishList.objects.create(user=request.user, product_id =prod_id)   
                    return JsonResponse({'status':'Product added successfully'}) 
            else: 
                return JsonResponse({'status':'No such product found'})  
        else:
            return JsonResponse({'status':'Login to continue'})              
    
    return redirect('products:home')






@login_required(login_url='accounts/login')
def deleteWishListItem(request):
    if request.method =="POST":
        if request.user.is_authenticated:
            prod_id =int(request.POST.get('product_id'))
            if WishList.objects.filter(user =request.user, product_id =prod_id):
                wishlistitem = WishList.objects.get(product_id =prod_id)
                wishlistitem.delete()
                return JsonResponse({'status':'Product already in wishlist'}) 

            else:
                return JsonResponse({'status':'Product not found'}) 

        else:
            return JsonResponse({'status':'Login to continue'})  
                       
    return redirect('products:home')



@login_required(login_url='accounts:login')
def checkoutItems(request):
    rawcart = Cart.objects.filter(user=request.user)

    #checking if quantity in the cart is greater than the available quantity
    for item in rawcart:
        if item.product_qty > item.product.quantity:
            Cart.objects.delete(id = item.id)


    cartItems =Cart.objects.filter(user = request.user)
    #item price and total price
    total_price =0
    for item in cartItems:
        total_price = total_price + item.product.selling_price * item.product_qty   

    context={"cartItems":cartItems,"total_price":total_price}
    return render(request,'shop/cartItems.html', context)
    #return render(request,'shop/checkout.html', context)



@login_required(login_url='accounts:login')
def placeOrder(request):
    if request.method == "POST":
        order = Order()
        order.user = request.user
        order.first_name = request.POST.get('first_name')
        order.last_name = request.POST.get('last_name')
        order.email = request.POST.get('email')
        order.phone = request.POST.get('phone')
        order.address = request.POST.get('address')
        order.city = request.POST.get('city')
        order.state = request.POST.get('state')
        order.country = request.POST.get('country')
        order.pin_code = request.POST.get('pin_code')
        order.payment_mode = request.POST.get('payment_mode')
        
        #total cart price
        cart = Cart.objects.filter(user = request.user)
        cart_total_price = 0 
        for item in cart:
            cart_total_price += item.product.selling_price * item.product_qty

        order.total_price = cart_total_price  

        #tracking no
        track_no ='nuelMobiles'+str(random.randint(1111111,9999999))  
        while Order.objects.filter(tracking_no=track_no) is None:
            track_no ='nuelMobiles'+str(random.randint(1111111,9999999))

        order.tracking_no =track_no

        order.save()   

        #orderitem products
        order_item_products = Cart.objects.filter(user = request.user)
        for item in order_item_products:
            OrderItem.objects.create(user=request.user, order = order, product=item.product, price =item.product.selling_price, 
                                     quantity =item.product_qty) 
            
            # reducing product quantity from available stock
            order_product =Product.objects.filter(id =item.product.id).first() 
            order_product.quantity = order_product.quantity -item.product_qty
            order_product.save()

        #to clear cart items

        #Cart.objects.filter(user=request.user).delete()
        
        

        if request.POST.get('payment_mode') == "online_payment":
            context ={ 'cart_total_price':cart_total_price}
            return render(request,'shop/card_payment.html',context)
        
        messages.info(request,"Order placed.Shippment on the way.Please get your cash ready.")
        Cart.objects.filter(user=request.user).delete()
        return redirect('/')





@login_required(login_url='accounts:login')
def razorpaycheckout(request):
    cart = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cart:
        total_price += item.product.selling_price * item.product_qty

    return JsonResponse({
        'total_price':total_price
    })    



             

def payment_confirmation(request):
    user = request.user
    
    #if Order.objects.filter(user=request.user, ordered =True).exists():

    messages.info(request,"Your order was successfully placed")
    return render(request,'payments/success.html')



def myOrders(request):
    if Order.objects.filter(user=request.user).exists():
        paid_orders =Order.objects.filter(user=request.user)

templates/shop/cartItems.html
{%extends 'layout/main.html' %}

{% block content %}
{% load static %}
{% load mathfilters %}

<style>
    a{
        text-decoration: none;
    }
    a:hover{
        text-decoration: underline;
    }

</style>
<div class="py-3 bg-primary">
    <div class="container">
        <a href="{% url 'products:home' %}" class="text-white">Home /</a>
        <a href="{% url 'products:checkout' %}" class="text-white">checkout /</a>
    </div>
</div>

{% if user.is_authenticated %}
<div class="container mt-3">
    <form action="{% url 'products:place_order' %}" method="POST">
        {% csrf_token %}
    <div class="row">
        <div class="col-md-7">
            <div class="card shadow">
                <div class="card-body">
                    <h6>Basic Details</h6>
                <hr>
                <div class="row checkoutform">
                    <div class="col-md-6">
                        <label for="">First Name</label>
                        <input type="text" name="first_name" value="{{ user.first_name}}" class="form-control" required  readonly class="form-control">
                    </div>  
                    <div class="col-md-6">
                        <label for="">Last Name</label>
                        <input type="text" name="last_name" value="{{ user.last_name}}" class="form-control" required  readonly class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">Email</label>
                        <input type="email" name="email" value="{{ user.email}}" class="form-control" required  readonly class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">Phone</label>
                        <input type="text" name="phone"  value="{{ user.customer.phone }}" class="form-control" required readonly class="form-control">
                    </div> 
                    <div class="col-md-12 mt-2">
                        <label for="">Address</label>
                        <textarea type="text" name="address" id="phone" class="form-control" required  placeholder="Enter address" class="form-control"></textarea>
                       
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">City</label>
                        <input type="text" name="city" id="city" class="form-control" required  placeholder="Enter city" class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">State</label>
                        <input type="text" name="state" id="state" class="form-control" required  placeholder="Enter state" class="form-control">
                    </div>  
                    <div class="col-md-6 mt-2">
                        <label for="">Pin Code</label>
                        <input type="text" name="pin_code" id="pin_code" class="form-control" required  placeholder="Enter code" class="form-control">
                    </div>
                    <div class="col-md-6 mt-2">
                        <label for="">Country</label>
                        <input type="text" name="country"  class="form-control" required placeholder="Enter country" class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">Payment Mode</label>
                        <select name="payment_mode" id="">
                            <option value="cod">Cash on Delivery</option>
                            <option value="online_payment">Card Payment</option>
                        </select>
                        <!--<label for="">Payment Mode</label>
                        <input type="text" name="payment_mode"  id="payment_mode" class="form-control" required placeholder="payment mode" class="form-control">-->
                    </div> 
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="card shadow">
            <div class="card-body">
                <h6>Order Summery</h6>
                <hr>
                {% if cartItems %}
                <table class="table table-stripeds table-bordered">
                    <tr>
                    <thead>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Amount</th>
                    </thead>
                    </tr>
                    <tbody>
                        
                            {% for item in cartItems %}
                            <tr>
                                <td><img src="{{item.product.img.url }}" height="50px" width="50px" class="me-3"> {{ item.product.name }}</td>
                                <td>{{ item.product_qty }}</td>
                                <td>{{ item.product.selling_price | stringformat:'d' }}</td>
                                <td><b>{{ item.product.selling_price|mul:item.product_qty  }}</b></td>
                            </tr>
                            {% endfor %}
                     
                    </tbody>
                </table>
                <h6 class="fw-bold">Grand Total 
                    <span class="float-end" id="amt">$ {{ total_price | stringformat:'d'}}</span>
                </h6>
                <div class="mt-3">
                    <BUtton type="submit" class="btn btn-success w-100" id="code" name="online payment">Submit</BUtton>
                    <!--<BUtton type="submit" class="btn btn-success w-100" id="code" name="online payment"> COD | Place Order</BUtton>
             
                <button type="button" id="card-payment" name="online payment" >online payment</button>
                <input type="button" value="Continue" class="btn btn-primary  w-100 mt-2">-->
                </div>
                {% else %}
                <h4>Your cart is empty</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    </form>
</div>

{% endif %}


{% endblock %}

{% block script %}


{% endblock script %}

templates/shop/checkout.html
{%extends 'layout/main.html' %}

{% block content %}
<style>
    a{
        text-decoration: none;
    }
    a:hover{
        text-decoration: underline;
    }

</style>
<div class="py-3 bg-primary">
    <div class="container">
        <a href="{% url 'products:home' %}" class="text-white">Home /</a>
        <a href="{% url 'products:checkout' %}" class="text-white">checkout /</a>
    </div>
</div>

<div class="container mt-3">
    <form action="{% url 'products:place_order' %}" method="POST">
        {% csrf_token %}
    <div class="row">
        <div class="col-md-7">
            <div class="card shadow">
                <div class="card-body">
                    <h6>Basic Details</h6>
                <hr>
                <div class="row checkoutform">
                    <div class="col-md-6">
                        <label for="">First Name</label>
                        <input type="text" name="first_name" class="form-control" required  placeholder="Enter first name" class="form-control">
                    </div>  
                    <div class="col-md-6">
                        <label for="">Last Name</label>
                        <input type="text" name="last_name" class="form-control" required  placeholder="Enter last name" class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">Email</label>
                        <input type="email" name="email" class="form-control" required  placeholder="Enter email address" class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">Phone</label>
                        <input type="text" name="phone"  class="form-control" required placeholder="Enter phone number" class="form-control">
                    </div> 
                    <div class="col-md-12 mt-2">
                        <label for="">Address</label>
                        <textarea type="text" name="address" class="form-control" required  placeholder="Enter address" class="form-control"></textarea>
                       
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">City</label>
                        <input type="text" name="city" class="form-control" required  placeholder="Enter city" class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">State</label>
                        <input type="text" name="state" class="form-control" required  placeholder="Enter state" class="form-control">
                    </div>  
                    <div class="col-md-6 mt-2">
                        <label for="">Pin Code</label>
                        <input type="text" name="pin_code" class="form-control" required  placeholder="Enter code" class="form-control">
                    </div>
                    <div class="col-md-6 mt-2">
                        <label for="">Country</label>
                        <input type="text" name="country"  class="form-control" required placeholder="Enter country" class="form-control">
                    </div> 
                    <div class="col-md-6 mt-2">
                        <label for="">Payment Mode</label>
                        <input type="text" name="payment_mode"  class="form-control" required placeholder="payment mode" class="form-control">
                    </div> 
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="card shadow">
            <div class="card-body">
                <h6>Order Summery</h6>
                <hr>
                {% if cartItems %}
                <table class="table table-stripeds table-bordered">
                    <tr>
                    <thead>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </thead>
                    </tr>
                    <tbody>
                        
                            {% for item in cartItems %}
                            <tr>
                                <td><img src="{{item.product.img.url }}" height="50px" width="50px" class="me-3"> {{ item.product.name }}</td>
                                <td>{{ item.product_qty }}</td>
                                <td>{{ item.product.selling_price | stringformat:'d' }}</td>
                            </tr>
                            {% endfor %}
                     
                    </tbody>
                </table>
                <h6 class="fw-bold">Grand Total 
                    <span class="float-end">$ {{ total_price | stringformat:'d'}}</span>
                </h6>
                <div class="mt-3">
                    <BUtton type="submit" class="btn btn-success w-100"> COD | Place Order</BUtton>
                <!--<a href="" class="btn btn-success w-100"> COD | Place Order</a>-->
                </div>
                {% else %}
                <h4>Your cart is empty</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    </form>
</div>

{% endblock %}

templates/shop/error.html
<h3>error</h3>

templates/shop/itmdetail.html
<h3>product details</h3>

<form action="{% url 'products:prod-request' %}" method="POST">
    {% csrf_token %}
    <h1>{{item.name}}</h1>product_name
   
    <input type="text" name="product_name" value="{{item.name}}" hidden>
    <h1>{{item.price}}</h1>
    <input type="number" name="price" value="{{item.price}}" hidden>
    <button class="btn btndanger">submit</button>
</form>

templates/shop/newlink.html
{% for itm in items %}
  <h3>{{itm.name}}</h3>
   <h4>{{itm.price}}</h4>
   <a href="{% url 'products:itmD' itm.pk %}">details</a>
{% endfor %}

templates/shop/productDetail.html
{%extends 'layout/main.html' %}

{% block content %}
<style>
    a{
        text-decoration: none;
    }
    a:hover{
        text-decoration: underline;
    }
</style>
<div class="py-3 bg-primary">
    <div class="container">
        <a href="{% url 'products:home' %}" class="text-white">Home /</a>
        <a href="{% url 'products:collection' %}" class="text-white">Collection /</a>
        <a href="{% url 'products:categoryitems' product.category.slug  %}" class="text-white">{{product.category.name}} /</a>
        <a href="{% url 'products:product_detail' product.category.slug product.slug   %}" class="text-white">{{product.name}}</a>
    </div>
</div>


<div class="py-5">
<div class="container">
    <form action="">
    <div class="row">
        <div class="col-md-12">
            <div class="card show product_data">
               
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            {% if product.tag %}
                            <label class="product-viewtag" for="">{{product.tag}}</label>
                            {% endif %}
                            <img src="{{ product.img.url }}" class="w-100" alt="">
                        </div>
                        <div class="col-md-8">
                            <h2 class="mb-0">
                                {{ product.name }}
                                {% if product.trending %}
                                <label for="" style="font-size: 16px;" class="float-end badge bg-danger trending-tag">trending</label>
                                {% endif %}
                            </h2>
                            <hr>
                            <label for="" class="me-3" > original price: <s> $ {{product.original_price |stringformat:'d'}}</s></label>
                            <label for="" class="fw-bold"> selling price: $ <strong style="color: green;" class="sales" id="sales"> {{product.selling_price |stringformat:'d'}} </strong></label>
                                <span class="float-end">total:<input type="text"  name="total" class="input-text total text-center text-center" value="{{product.selling_price |stringformat:'d'}}"  readonly></span>
                          
                            <p class="mt-3">
                                {{ product.small_description }}
                            </p>
                            <hr>
                            {% if product.quantity > 0 %}
                            <label for="" class="bg-success badge"> in stock</label>
                            {% else %}
                            <label for="" class="bg-success badge"> out of stock stock</label>
                            {% endif %}
                            <div class="row mt-2">
                                <div class="col-md-3">
                                   {% csrf_token %}
                                   
                                    <input type="hidden" name="prod_id" value="{{ product.id }}" class="prod_id">
                                    <label class="quantity">quantity</label>
                                    <div class="input-group text-center mb-3" style="width: 130px;">
                                        <button class="input-group-text decrement-btn ">-</button>
                                        <input type="text" name="quantity" class="form-control qty-input text-center text-center" value="1">
                                        <button class="input-group-text increment-btn">+</button>

                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <br>
                                    
                                    {% if product.quantity > 0 %}
                                    <button class="btn btn-primary me-3 float-start addToCart" type="button">add to cart <i class=" fa fa-shopping-cart"></i></a>
                                    {% endif %}
                                    <button class="btn btn-success me-3  addToWishlist float-start" type="button">add to wishlist <i class=" fa fa-heart"></i></button>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <hr>
                        <h3>description</h3>
                        <p class="mt-3">{{product.description}}</p>
                    </div>
                </div>
                </form>
             

            </div>
        </div>
    </div>
 
</div>
</div>

<script>
    
      
    
</script>


{% endblock %}